about: docs/about.md
description: StackSpot Data Apache Spark
display-name: Apache Spark
category: Analytics
compatibility:
  - Python
name: stackspot-data-apache-spark
picture: stack.png
technologies:
  - Apache Spark
  - Python
