about: docs/about.md
description: StackSpot Data Apache Spark
display-name: Apache Spark
category: Data
compatibility:
  - Python
name: stackspot-data-apache-spark
technologies:
  - Apache Spark
  - Python
